export const provinces = [
  { name: 'Western', code: 'WP' },
  { name: 'Central', code: 'CP' },
  { name: 'Southern', code: 'SP' },
  { name: 'Northern', code: 'NP' },
  { name: 'Eastern', code: 'EP' },
  { name: 'North Western', code: 'NWP' },
  { name: 'North Central', code: 'NCP' },
  { name: 'Uva', code: 'UP' },
  { name: 'Sabaragamuwa', code: 'SGP' },
];

export const districts = [
  { name: 'Colombo', code: 'COL', provinceName: 'Western' },
  { name: 'Gampaha', code: 'GAM', provinceName: 'Western' },
  { name: 'Kalutara', code: 'KAL', provinceName: 'Western' },
  { name: 'Kandy', code: 'KAN', provinceName: 'Central' },
  { name: 'Matale', code: 'MAT', provinceName: 'Central' },
  { name: 'Nuwara Eliya', code: 'NUW', provinceName: 'Central' },
  { name: 'Galle', code: 'GAL', provinceName: 'Southern' },
  { name: 'Matara', code: 'MTR', provinceName: 'Southern' },
  { name: 'Hambantota', code: 'HAM', provinceName: 'Southern' },
  { name: 'Jaffna', code: 'JAF', provinceName: 'Northern' },
  { name: 'Kilinochchi', code: 'KIL', provinceName: 'Northern' },
  { name: 'Mannar', code: 'MAN', provinceName: 'Northern' },
  { name: 'Vavuniya', code: 'VAV', provinceName: 'Northern' },
  { name: 'Mullaitivu', code: 'MUL', provinceName: 'Northern' },
  { name: 'Batticaloa', code: 'BAT', provinceName: 'Eastern' },
  { name: 'Ampara', code: 'AMP', provinceName: 'Eastern' },
  { name: 'Trincomalee', code: 'TRI', provinceName: 'Eastern' },
  { name: 'Kurunegala', code: 'KUR', provinceName: 'North Western' },
  { name: 'Puttalam', code: 'PUT', provinceName: 'North Western' },
  { name: 'Anuradhapura', code: 'ANU', provinceName: 'North Central' },
  { name: 'Polonnaruwa', code: 'POL', provinceName: 'North Central' },
  { name: 'Badulla', code: 'BAD', provinceName: 'Uva' },
  { name: 'Monaragala', code: 'MON', provinceName: 'Uva' },
  { name: 'Ratnapura', code: 'RAT', provinceName: 'Sabaragamuwa' },
  { name: 'Kegalle', code: 'KEG', provinceName: 'Sabaragamuwa' },
];

export const policeStations = [
  { name: 'Colombo Fort Police Station', code: 'PS001', districtName: 'Colombo' },
  { name: 'Wellawatte Police Station', code: 'PS002', districtName: 'Colombo' },
  { name: 'Nugegoda Police Station', code: 'PS003', districtName: 'Colombo' },
  { name: 'Dehiwala Police Station', code: 'PS004', districtName: 'Colombo' },
  { name: 'Kelaniya Police Station', code: 'PS005', districtName: 'Gampaha' },
  { name: 'Negombo Police Station', code: 'PS006', districtName: 'Gampaha' },
  { name: 'Gampaha Police Station', code: 'PS007', districtName: 'Gampaha' },
  { name: 'Kalutara Police Station', code: 'PS008', districtName: 'Kalutara' },
  { name: 'Panadura Police Station', code: 'PS009', districtName: 'Kalutara' },
  { name: 'Kandy Police Station', code: 'PS010', districtName: 'Kandy' },
  { name: 'Peradeniya Police Station', code: 'PS011', districtName: 'Kandy' },
  { name: 'Matale Police Station', code: 'PS012', districtName: 'Matale' },
  { name: 'Nuwara Eliya Police Station', code: 'PS013', districtName: 'Nuwara Eliya' },
  { name: 'Galle Police Station', code: 'PS014', districtName: 'Galle' },
  { name: 'Hikkaduwa Police Station', code: 'PS015', districtName: 'Galle' },
  { name: 'Matara Police Station', code: 'PS016', districtName: 'Matara' },
  { name: 'Hambantota Police Station', code: 'PS017', districtName: 'Hambantota' },
  { name: 'Jaffna Police Station', code: 'PS018', districtName: 'Jaffna' },
  { name: 'Trincomalee Police Station', code: 'PS019', districtName: 'Trincomalee' },
  { name: 'Kurunegala Police Station', code: 'PS020', districtName: 'Kurunegala' },
  { name: 'Anuradhapura Police Station', code: 'PS021', districtName: 'Anuradhapura' },
  { name: 'Badulla Police Station', code: 'PS022', districtName: 'Badulla' },
  { name: 'Ratnapura Police Station', code: 'PS023', districtName: 'Ratnapura' },
  { name: 'Batticaloa Police Station', code: 'PS024', districtName: 'Batticaloa' },
  { name: 'Kegalle Police Station', code: 'PS025', districtName: 'Kegalle' },
];